COberm/issue7
openBackhaul/MediatorManager pull request #14
Opened 2022-11-10 14:51 UTC by COberm

Fixes #7

2022-11-10 14:58 UTC, COberm commented
ServiceList aktualisiert und an neues Template angepasst

2022-11-22 14:36 UTC, kmohr-soprasteria commented on ApplicationPattern+services.yaml
> +          uuid: mm-1-0-0-op-s-bs-004
es gibt noch einen neuen basic service:
        - service-name: /docs
          uuid: xx-1-0-0-op-s-bs-005

2022-11-22 14:38 UTC, kmohr-soprasteria commented on ApplicationPattern+services.yaml
> +        - service-name: /v1/provide-mediator
hier die Sequence-Nummer in den uuids ändern (-000 wird ja wieder frei)

2022-11-22 14:39 UTC, kmohr-soprasteria commented on ApplicationPattern+services.yaml
> +  tcp-server:
hier gab es ein Template-Update:
  tcp-server:
    - description: Without TLS layer
      local-protocol: http
      own-ip-address: ## TODO: Add OwnIpAddress
      own-tcp-port: ## TODO: Add OwnTcpPort
      uuid: xx-1-0-0-tcp-s-bm-000
    - description: With TLS layer
      local-protocol: https
      own-ip-address: ## TODO: Add OwnIpAddress
      own-tcp-port: ## TODO: Add OwnTcpPort
      uuid: xx-1-0-0-tcp-s-bm-001

2022-11-22 14:45 UTC, kmohr-soprasteria commented on ApplicationPattern+services.yaml
new http-client for elastic search to be added:
  - http-client:
      application-name: ElasticSearch
      release-number: 1.0.0
      uuid: xx-1-0-0-http-c-is-es-1-0-0-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.3.15
      tcp-port: 3015
      uuid: xx-1-0-0-tcp-c-is-es-1-0-0-000
    elasticsearch-client:
      uuid: xx-1-0-0-es-c-is-es-1-0-0-000
      index-alias: ## TODO: Add IndexAlias

2022-11-22 14:46 UTC, kmohr-soprasteria commented on ApplicationPattern+services.yaml
>    - http-client:
can be removed if not used

2022-11-22 14:46 UTC, kmohr-soprasteria requested changes
see inline comments

2022-12-02 10:09 UTC, kmohr-soprasteria approved these changes

2022-12-02 10:09 UTC, kmohr-soprasteria commented
elasticsearch question will be handled in separate issue

2022-12-02 10:10 UTC, merged